### ISSUE TITLE
A way to return to the original copy of the data

### ISSUE THREAD

**Issue by josphh** [danth/yamte#4]
### Description

Some sort of way to return to the original state of a file, of when it was last saved. 

### Advantages

Good for when you don't want to close yamte, but you want to have a fresh "slate" to work with, undoing all your mistakes.

### Implementation details

Probably sommat like CTRL Z, but that might be infuriating to users expecting to undo, so add a confirmation dialogue

**Comment by danth** [comment]
Maybe `ctrl-shift-z` to re-read the file, and in future, `ctrl-z` as undo.

**Comment by danth** [comment]
Use `f` followed by `r` to reload the file.
