### ISSUE TITLE
Pressing Tab uses 8 spaces instead of 4

### ISSUE THREAD

**Issue by josphh** [danth/yamte#9]
### Current behaviour

Using the TAB key uses 8 spaces instead of the standard 4

### Expected behaviour

For the TAB key to use 4 spaces

**Comment by danth** [comment]
Pressing tab actually creates a tab character, which is displayed as 8 spaces. Should it be displayed as 4 instead?

**Comment by josphh** [comment]
Usually the standard for TAB keys is 4 spaces, as shown in apps like VSCode, and the default Rust `main.rs` file. Maybe this could be made configurable?
